FROM elixir:1.16-alpine

RUN apk add --no-cache build-base git nodejs npm inotify-tools postgresql-client curl aws-cli

WORKDIR /app

COPY mix.exs mix.lock ./
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get && \
    mix deps.compile

COPY . .

EXPOSE 4000

CMD ["mix", "phx.server"]
